### ISSUE TITLE
fingerprintJson 示例文件

### ISSUE THREAD

**Issue by Drlee00** [FPEsocrter/openFpchromium#1]
hello，能否上传指纹json文件？

**Comment by FPEsocrter** [comment]
> hello，能否上传指纹json文件？

没有时间处理这个，5月份的时候吧

**Comment by FPEsocrter** [comment]
放弃公开， 有人写了一个脚本说用于这个项目 ，说写的不容易， 暂时不想公开，好 好  好，  就我一个人写的容易行吧  ，项目 应该不会去更新其他的，  我准备提供免费的版本就好
