### ISSUE TITLE
更新内核，还是功能

### ISSUE THREAD

**Issue by FPEsocrter** [FPEsocrter/openFpchromium#3]
24.5.1 后继续开发 
采用最新的内核版本 视频编译教程，指纹说明 和启动的参数json说明 收费(500左右) 可以完整指纹浏览器， 可以过指纹检查网站的 配置的json 都是合理的， 需要的有优先处理这个。 如果不需要的，我就继续开发其他 （客户端的代码 和成品有关系的东西了 ）

**Comment by FPEsocrter** [comment]
以选择开发 124.0.6367.119内核

**Comment by FPEsocrter** [comment]
新的内核也暂停了，  后续不开源

**Comment by icew4y** [comment]
@FPEsocrter 佬，我想买课怎么联系？我V: LouisWong2099
