### ISSUE TITLE
有人想一起开发吗？

### ISSUE THREAD

**Issue by FPEsocrter** [FPEsocrter/openFpchromium#4]
我现在一个人是开发整个项目，忙不过来，项目技术  c++chromiun 内核部分  客户端vue+go  管理系统java
 

现在最缺go和vue

有兴趣的联系我

**Comment by pretty66** [comment]
我可以做vue+go的部分，怎么联系你

**Comment by FPEsocrter** [comment]
> 我可以做vue+go的部分，怎么联系你

加群找我

**Comment by li161** [comment]
> 我可以做vue+go的部分，怎么联系你

你们做好了吗

**Comment by sqh007** [comment]
还需要vue吗？

**Comment by li161** [comment]
> 还需要vue吗？

你看懂代码了吗，咱们一起做不？
